ARG FEDORA_VERSION=38

# Use Fedora as the base image
FROM registry.fedoraproject.org/fedora:${FEDORA_VERSION}

# Install build dependencies
RUN dnf -y install \
    copr-cli \
    fedora-packager \
    ImageMagick \
    mock \
    rpm-build \
    rpmdevtools \
    && dnf clean all
